# Generated by Django 3.1.7 on 2021-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0003_remove_reservation_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationapp',
            name='user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
